spring:
  datasource:
    url: jdbc:mysql:///athenapharmacydb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
Store:
  storeNo: 500
  storeName: Sahoo Pharmacy
  storeCity: Rourkela
  storeState: Odisha
  storePinCode: 769011